import type { Question } from "./types";

// ── HISTORY & CIVICS (Grade 6-12) ────────────────────────────────────────────

export const HUMANITIES_HISTORY: Question[] = [
  { id:"hh1", type:"mcq", title:"India gained independence from British rule on:", options:[{id:"a",text:"15 August 1945",isCorrect:false},{id:"b",text:"15 August 1947",isCorrect:true},{id:"c",text:"26 January 1950",isCorrect:false},{id:"d",text:"2 October 1947",isCorrect:false}], xpReward:10 },
  { id:"hh2", type:"mcq", title:"Who wrote the Indian constitution?", options:[{id:"a",text:"Mahatma Gandhi",isCorrect:false},{id:"b",text:"Jawaharlal Nehru",isCorrect:false},{id:"c",text:"Dr. B.R. Ambedkar",isCorrect:true},{id:"d",text:"Sardar Patel",isCorrect:false}], xpReward:10 },
  { id:"hh3", type:"mcq", title:"The First World War was fought from:", options:[{id:"a",text:"1910–1914",isCorrect:false},{id:"b",text:"1914–1918",isCorrect:true},{id:"c",text:"1918–1922",isCorrect:false},{id:"d",text:"1939–1945",isCorrect:false}], xpReward:10 },
  { id:"hh4", type:"mcq", title:"The French Revolution began in:", options:[{id:"a",text:"1776",isCorrect:false},{id:"b",text:"1789",isCorrect:true},{id:"c",text:"1800",isCorrect:false},{id:"d",text:"1815",isCorrect:false}], xpReward:10 },
  { id:"hh5", type:"mcq", title:"Who discovered America in 1492?", options:[{id:"a",text:"Vasco da Gama",isCorrect:false},{id:"b",text:"Ferdinand Magellan",isCorrect:false},{id:"c",text:"Christopher Columbus",isCorrect:true},{id:"d",text:"Marco Polo",isCorrect:false}], xpReward:10 },
  { id:"hh6", type:"mcq", title:"The United Nations was founded in:", options:[{id:"a",text:"1919",isCorrect:false},{id:"b",text:"1939",isCorrect:false},{id:"c",text:"1945",isCorrect:true},{id:"d",text:"1950",isCorrect:false}], xpReward:10 },
  { id:"hh7", type:"mcq", title:"India's Republic Day is celebrated on:", options:[{id:"a",text:"15 August",isCorrect:false},{id:"b",text:"2 October",isCorrect:false},{id:"c",text:"26 January",isCorrect:true},{id:"d",text:"1 November",isCorrect:false}], xpReward:10 },
  { id:"hh8", type:"mcq", title:"The Industrial Revolution began in which country?", options:[{id:"a",text:"France",isCorrect:false},{id:"b",text:"Germany",isCorrect:false},{id:"c",text:"United Kingdom",isCorrect:true},{id:"d",text:"United States",isCorrect:false}], xpReward:10 },
];

export const HUMANITIES_GEOGRAPHY: Question[] = [
  { id:"hg1", type:"mcq", title:"Which is the largest continent by area?", options:[{id:"a",text:"Africa",isCorrect:false},{id:"b",text:"North America",isCorrect:false},{id:"c",text:"Asia",isCorrect:true},{id:"d",text:"Europe",isCorrect:false}], xpReward:10 },
  { id:"hg2", type:"mcq", title:"Which is the longest river in the world?", options:[{id:"a",text:"Amazon",isCorrect:false},{id:"b",text:"Nile",isCorrect:true},{id:"c",text:"Yangtze",isCorrect:false},{id:"d",text:"Mississippi",isCorrect:false}], xpReward:10 },
  { id:"hg3", type:"mcq", title:"The Tropic of Cancer passes through which Indian state?", options:[{id:"a",text:"Kerala",isCorrect:false},{id:"b",text:"Gujarat",isCorrect:true},{id:"c",text:"Rajasthan",isCorrect:false},{id:"d",text:"Tamil Nadu",isCorrect:false}], xpReward:10 },
  { id:"hg4", type:"mcq", title:"Mount Everest is located in:", options:[{id:"a",text:"India",isCorrect:false},{id:"b",text:"Tibet only",isCorrect:false},{id:"c",text:"Nepal/Tibet border",isCorrect:true},{id:"d",text:"Pakistan",isCorrect:false}], xpReward:10 },
  { id:"hg5", type:"mcq", title:"What causes seasons on Earth?", options:[{id:"a",text:"Distance from the Sun",isCorrect:false},{id:"b",text:"Earth's tilted axis as it orbits the Sun",isCorrect:true},{id:"c",text:"The Moon's gravity",isCorrect:false},{id:"d",text:"Ocean currents",isCorrect:false}], xpReward:10 },
  { id:"hg6", type:"mcq", title:"The Sahara is what type of desert?", options:[{id:"a",text:"Cold desert",isCorrect:false},{id:"b",text:"Coastal desert",isCorrect:false},{id:"c",text:"Hot and dry desert",isCorrect:true},{id:"d",text:"Semi-arid desert",isCorrect:false}], xpReward:10 },
  { id:"hg7", type:"mcq", title:"How many countries share a border with India?", options:[{id:"a",text:"5",isCorrect:false},{id:"b",text:"6",isCorrect:false},{id:"c",text:"7",isCorrect:true},{id:"d",text:"9",isCorrect:false}], xpReward:10 },
  { id:"hg8", type:"mcq", title:"Which ocean is the largest?", options:[{id:"a",text:"Atlantic",isCorrect:false},{id:"b",text:"Indian",isCorrect:false},{id:"c",text:"Pacific",isCorrect:true},{id:"d",text:"Arctic",isCorrect:false}], xpReward:10 },
];

export const HUMANITIES_ECONOMICS: Question[] = [
  { id:"he1", type:"mcq", title:"GDP stands for:", options:[{id:"a",text:"General Development Plan",isCorrect:false},{id:"b",text:"Gross Domestic Product",isCorrect:true},{id:"c",text:"Government Deficit Programme",isCorrect:false},{id:"d",text:"Global Development Price",isCorrect:false}], xpReward:10 },
  { id:"he2", type:"mcq", title:"Inflation refers to:", options:[{id:"a",text:"Decrease in price levels",isCorrect:false},{id:"b",text:"Sustained increase in general price levels",isCorrect:true},{id:"c",text:"Decrease in GDP",isCorrect:false},{id:"d",text:"Increase in employment",isCorrect:false}], xpReward:10 },
  { id:"he3", type:"mcq", title:"The law of demand states: as price increases, demand:", options:[{id:"a",text:"Increases",isCorrect:false},{id:"b",text:"Stays the same",isCorrect:false},{id:"c",text:"Decreases",isCorrect:true},{id:"d",text:"Doubles",isCorrect:false}], xpReward:10 },
  { id:"he4", type:"mcq", title:"Which bank controls monetary policy in India?", options:[{id:"a",text:"SBI",isCorrect:false},{id:"b",text:"Reserve Bank of India",isCorrect:true},{id:"c",text:"HDFC Bank",isCorrect:false},{id:"d",text:"SEBI",isCorrect:false}], xpReward:10 },
  { id:"he5", type:"mcq", title:"A monopoly market has:", options:[{id:"a",text:"Many buyers and sellers",isCorrect:false},{id:"b",text:"Only one seller",isCorrect:true},{id:"c",text:"Only one buyer",isCorrect:false},{id:"d",text:"Two sellers",isCorrect:false}], xpReward:10 },
  { id:"he6", type:"mcq", title:"Opportunity cost means:", options:[{id:"a",text:"The monetary cost of a product",isCorrect:false},{id:"b",text:"The value of the next best alternative forgone",isCorrect:true},{id:"c",text:"The cost of production",isCorrect:false},{id:"d",text:"The tax paid on a good",isCorrect:false}], xpReward:10 },
  { id:"he7", type:"mcq", title:"FDI stands for:", options:[{id:"a",text:"Foreign Domestic Investment",isCorrect:false},{id:"b",text:"Fixed Deposit Interest",isCorrect:false},{id:"c",text:"Foreign Direct Investment",isCorrect:true},{id:"d",text:"Financial Development Index",isCorrect:false}], xpReward:10 },
  { id:"he8", type:"mcq", title:"A budget deficit occurs when:", options:[{id:"a",text:"Revenue exceeds expenditure",isCorrect:false},{id:"b",text:"Expenditure exceeds revenue",isCorrect:true},{id:"c",text:"Revenue equals expenditure",isCorrect:false},{id:"d",text:"Exports exceed imports",isCorrect:false}], xpReward:10 },
];

// ── COMPUTER SCIENCE (Grade 6 → Higher Ed) ────────────────────────────────────

export const CS_PROGRAMMING_BASICS: Question[] = [
  { id:"cs1", type:"mcq", title:"What does HTML stand for?", options:[{id:"a",text:"Hyper Transfer Markup Language",isCorrect:false},{id:"b",text:"HyperText Markup Language",isCorrect:true},{id:"c",text:"High Text Modern Language",isCorrect:false},{id:"d",text:"HyperText Machine Language",isCorrect:false}], xpReward:10 },
  { id:"cs2", type:"mcq", title:"Which of these is NOT a programming language?", options:[{id:"a",text:"Python",isCorrect:false},{id:"b",text:"Java",isCorrect:false},{id:"c",text:"HTTP",isCorrect:true},{id:"d",text:"C++",isCorrect:false}], xpReward:10 },
  { id:"cs3", type:"mcq", title:"In programming, a 'loop' is used to:", options:[{id:"a",text:"Stop the program",isCorrect:false},{id:"b",text:"Repeat a block of code",isCorrect:true},{id:"c",text:"Define a variable",isCorrect:false},{id:"d",text:"Store data permanently",isCorrect:false}], xpReward:10 },
  { id:"cs4", type:"mcq", title:"What is a variable in programming?", options:[{id:"a",text:"A fixed value that never changes",isCorrect:false},{id:"b",text:"A named storage location for data",isCorrect:true},{id:"c",text:"A type of loop",isCorrect:false},{id:"d",text:"A function that runs automatically",isCorrect:false}], xpReward:10 },
  { id:"cs5", type:"mcq", title:"Which symbol is used for comments in Python?", options:[{id:"a",text:"//",isCorrect:false},{id:"b",text:"/* */",isCorrect:false},{id:"c",text:"#",isCorrect:true},{id:"d",text:"--",isCorrect:false}], xpReward:10 },
  { id:"cs6", type:"mcq", title:"What does CSS stand for?", options:[{id:"a",text:"Cascading Style Sheets",isCorrect:true},{id:"b",text:"Computer Style System",isCorrect:false},{id:"c",text:"Creative Styling Standard",isCorrect:false},{id:"d",text:"Coded Style Script",isCorrect:false}], xpReward:10 },
  { id:"cs7", type:"mcq", title:"Binary number 1010 equals which decimal?", options:[{id:"a",text:"8",isCorrect:false},{id:"b",text:"10",isCorrect:true},{id:"c",text:"12",isCorrect:false},{id:"d",text:"14",isCorrect:false}], xpReward:10 },
  { id:"cs8", type:"mcq", title:"An 'if-else' statement is used for:", options:[{id:"a",text:"Repeating code",isCorrect:false},{id:"b",text:"Storing values",isCorrect:false},{id:"c",text:"Decision making / conditional execution",isCorrect:true},{id:"d",text:"Defining functions",isCorrect:false}], xpReward:10 },
];

export const CS_DATA_STRUCTURES: Question[] = [
  { id:"csd1", type:"mcq", title:"Which data structure follows LIFO (Last In First Out)?", options:[{id:"a",text:"Queue",isCorrect:false},{id:"b",text:"Stack",isCorrect:true},{id:"c",text:"Linked List",isCorrect:false},{id:"d",text:"Tree",isCorrect:false}], xpReward:10 },
  { id:"csd2", type:"mcq", title:"Which data structure follows FIFO (First In First Out)?", options:[{id:"a",text:"Stack",isCorrect:false},{id:"b",text:"Queue",isCorrect:true},{id:"c",text:"Graph",isCorrect:false},{id:"d",text:"Array",isCorrect:false}], xpReward:10 },
  { id:"csd3", type:"mcq", title:"Time complexity of Binary Search is:", options:[{id:"a",text:"O(n)",isCorrect:false},{id:"b",text:"O(n²)",isCorrect:false},{id:"c",text:"O(log n)",isCorrect:true},{id:"d",text:"O(1)",isCorrect:false}], xpReward:10 },
  { id:"csd4", type:"mcq", title:"An array in programming:", options:[{id:"a",text:"Stores a single value",isCorrect:false},{id:"b",text:"Stores multiple values of the same type under one name",isCorrect:true},{id:"c",text:"Is used only for sorting",isCorrect:false},{id:"d",text:"Cannot be modified",isCorrect:false}], xpReward:10 },
  { id:"csd5", type:"mcq", title:"A linked list node contains:", options:[{id:"a",text:"Only data",isCorrect:false},{id:"b",text:"Data and a pointer to the next node",isCorrect:true},{id:"c",text:"Only a pointer",isCorrect:false},{id:"d",text:"An index number",isCorrect:false}], xpReward:10 },
  { id:"csd6", type:"mcq", title:"Which sorting algorithm is fastest on average?", options:[{id:"a",text:"Bubble Sort",isCorrect:false},{id:"b",text:"Selection Sort",isCorrect:false},{id:"c",text:"Quick Sort",isCorrect:true},{id:"d",text:"Insertion Sort",isCorrect:false}], xpReward:10 },
  { id:"csd7", type:"mcq", title:"A tree with no children is called:", options:[{id:"a",text:"Root node",isCorrect:false},{id:"b",text:"Branch node",isCorrect:false},{id:"c",text:"Leaf node",isCorrect:true},{id:"d",text:"Parent node",isCorrect:false}], xpReward:10 },
  { id:"csd8", type:"mcq", title:"What does SQL stand for?", options:[{id:"a",text:"Structured Query Language",isCorrect:true},{id:"b",text:"Simple Query Logic",isCorrect:false},{id:"c",text:"Standard Question Language",isCorrect:false},{id:"d",text:"Sequential Queue Logic",isCorrect:false}], xpReward:10 },
];

export const CS_NETWORKS: Question[] = [
  { id:"cn1", type:"mcq", title:"What does IP stand for in networking?", options:[{id:"a",text:"Internet Protocol",isCorrect:true},{id:"b",text:"Internal Processing",isCorrect:false},{id:"c",text:"Integrated Platform",isCorrect:false},{id:"d",text:"Information Package",isCorrect:false}], xpReward:10 },
  { id:"cn2", type:"mcq", title:"HTTP stands for:", options:[{id:"a",text:"HyperText Transfer Protocol",isCorrect:true},{id:"b",text:"High Transfer Text Platform",isCorrect:false},{id:"c",text:"Hosted Text Transfer Processor",isCorrect:false},{id:"d",text:"HyperText Tracking Protocol",isCorrect:false}], xpReward:10 },
  { id:"cn3", type:"mcq", title:"Which layer of the OSI model handles routing?", options:[{id:"a",text:"Physical",isCorrect:false},{id:"b",text:"Data Link",isCorrect:false},{id:"c",text:"Network",isCorrect:true},{id:"d",text:"Transport",isCorrect:false}], xpReward:10 },
  { id:"cn4", type:"mcq", title:"A firewall is used to:", options:[{id:"a",text:"Speed up internet connection",isCorrect:false},{id:"b",text:"Monitor and control incoming/outgoing network traffic",isCorrect:true},{id:"c",text:"Store website data",isCorrect:false},{id:"d",text:"Assign IP addresses",isCorrect:false}], xpReward:10 },
  { id:"cn5", type:"mcq", title:"DNS stands for:", options:[{id:"a",text:"Dynamic Name System",isCorrect:false},{id:"b",text:"Domain Name System",isCorrect:true},{id:"c",text:"Data Network Service",isCorrect:false},{id:"d",text:"Digital Node System",isCorrect:false}], xpReward:10 },
  { id:"cn6", type:"mcq", title:"Which protocol is used for sending email?", options:[{id:"a",text:"FTP",isCorrect:false},{id:"b",text:"HTTP",isCorrect:false},{id:"c",text:"SMTP",isCorrect:true},{id:"d",text:"SSH",isCorrect:false}], xpReward:10 },
  { id:"cn7", type:"mcq", title:"A LAN (Local Area Network) covers:", options:[{id:"a",text:"An entire country",isCorrect:false},{id:"b",text:"Multiple cities",isCorrect:false},{id:"c",text:"A small area like a building or campus",isCorrect:true},{id:"d",text:"The entire internet",isCorrect:false}], xpReward:10 },
  { id:"cn8", type:"mcq", title:"HTTPS is more secure than HTTP because it uses:", options:[{id:"a",text:"Faster servers",isCorrect:false},{id:"b",text:"Encryption (SSL/TLS)",isCorrect:true},{id:"c",text:"Larger data packets",isCorrect:false},{id:"d",text:"A different port number only",isCorrect:false}], xpReward:10 },
];

// ── HIGHER EDUCATION (College/University Level) ────────────────────────────────

export const HIGHER_DBMS: Question[] = [
  { id:"db1", type:"mcq", title:"In a relational database, a PRIMARY KEY:", options:[{id:"a",text:"Can have duplicate values",isCorrect:false},{id:"b",text:"Uniquely identifies each row in a table",isCorrect:true},{id:"c",text:"Links two tables",isCorrect:false},{id:"d",text:"Is always a number",isCorrect:false}], xpReward:10 },
  { id:"db2", type:"mcq", title:"Which SQL command retrieves data from a table?", options:[{id:"a",text:"INSERT",isCorrect:false},{id:"b",text:"UPDATE",isCorrect:false},{id:"c",text:"SELECT",isCorrect:true},{id:"d",text:"DELETE",isCorrect:false}], xpReward:10 },
  { id:"db3", type:"mcq", title:"Normalisation in databases aims to:", options:[{id:"a",text:"Speed up queries",isCorrect:false},{id:"b",text:"Reduce data redundancy and improve integrity",isCorrect:true},{id:"c",text:"Increase storage space",isCorrect:false},{id:"d",text:"Add more tables",isCorrect:false}], xpReward:10 },
  { id:"db4", type:"mcq", title:"A FOREIGN KEY in a table:", options:[{id:"a",text:"Is the main identifier of the table",isCorrect:false},{id:"b",text:"References a primary key in another table",isCorrect:true},{id:"c",text:"Cannot be NULL",isCorrect:false},{id:"d",text:"Is automatically generated",isCorrect:false}], xpReward:10 },
  { id:"db5", type:"mcq", title:"What is a JOIN in SQL?", options:[{id:"a",text:"A way to delete records",isCorrect:false},{id:"b",text:"A way to combine rows from two or more tables",isCorrect:true},{id:"c",text:"A way to create a new table",isCorrect:false},{id:"d",text:"A way to backup data",isCorrect:false}], xpReward:10 },
  { id:"db6", type:"mcq", title:"ACID in database transactions stands for:", options:[{id:"a",text:"Atomicity, Consistency, Isolation, Durability",isCorrect:true},{id:"b",text:"Access, Control, Index, Data",isCorrect:false},{id:"c",text:"Algorithm, Coding, Integration, Design",isCorrect:false},{id:"d",text:"Atomicity, Coding, Index, Durability",isCorrect:false}], xpReward:10 },
  { id:"db7", type:"mcq", title:"Which normal form eliminates partial dependencies?", options:[{id:"a",text:"1NF",isCorrect:false},{id:"b",text:"2NF",isCorrect:true},{id:"c",text:"3NF",isCorrect:false},{id:"d",text:"BCNF",isCorrect:false}], xpReward:10 },
  { id:"db8", type:"mcq", title:"NoSQL databases are best suited for:", options:[{id:"a",text:"Highly structured relational data",isCorrect:false},{id:"b",text:"Unstructured or semi-structured large-scale data",isCorrect:true},{id:"c",text:"Small datasets only",isCorrect:false},{id:"d",text:"Financial transaction data exclusively",isCorrect:false}], xpReward:10 },
];

export const HIGHER_OS: Question[] = [
  { id:"os1", type:"mcq", title:"What is the primary function of an Operating System?", options:[{id:"a",text:"Browse the internet",isCorrect:false},{id:"b",text:"Manage hardware resources and provide services to programs",isCorrect:true},{id:"c",text:"Run antivirus scans",isCorrect:false},{id:"d",text:"Store files permanently",isCorrect:false}], xpReward:10 },
  { id:"os2", type:"mcq", title:"Which scheduling algorithm gives priority to the shortest job?", options:[{id:"a",text:"FCFS",isCorrect:false},{id:"b",text:"Round Robin",isCorrect:false},{id:"c",text:"SJF (Shortest Job First)",isCorrect:true},{id:"d",text:"Priority Scheduling",isCorrect:false}], xpReward:10 },
  { id:"os3", type:"mcq", title:"Deadlock in an OS occurs when:", options:[{id:"a",text:"A process uses too much CPU",isCorrect:false},{id:"b",text:"Two or more processes wait indefinitely for each other's resources",isCorrect:true},{id:"c",text:"Memory is full",isCorrect:false},{id:"d",text:"A process crashes",isCorrect:false}], xpReward:10 },
  { id:"os4", type:"mcq", title:"Virtual memory allows:", options:[{id:"a",text:"Programs to run faster",isCorrect:false},{id:"b",text:"Use of disk space as an extension of RAM",isCorrect:true},{id:"c",text:"Deletion of unused files",isCorrect:false},{id:"d",text:"Sharing of CPU between users",isCorrect:false}], xpReward:10 },
  { id:"os5", type:"mcq", title:"A process in the 'blocked' state is waiting for:", options:[{id:"a",text:"CPU time",isCorrect:false},{id:"b",text:"An I/O event or resource to become available",isCorrect:true},{id:"c",text:"Memory allocation",isCorrect:false},{id:"d",text:"Another process to terminate",isCorrect:false}], xpReward:10 },
  { id:"os6", type:"mcq", title:"Paging in memory management helps in:", options:[{id:"a",text:"Sorting files",isCorrect:false},{id:"b",text:"Eliminating external fragmentation",isCorrect:true},{id:"c",text:"Increasing CPU speed",isCorrect:false},{id:"d",text:"Scheduling processes",isCorrect:false}], xpReward:10 },
  { id:"os7", type:"mcq", title:"Which is NOT an OS type?", options:[{id:"a",text:"Batch OS",isCorrect:false},{id:"b",text:"Real-Time OS",isCorrect:false},{id:"c",text:"Distributed OS",isCorrect:false},{id:"d",text:"Compiled OS",isCorrect:true}], xpReward:10 },
  { id:"os8", type:"mcq", title:"A thread differs from a process because:", options:[{id:"a",text:"Threads cannot run simultaneously",isCorrect:false},{id:"b",text:"Threads share the same memory space of their parent process",isCorrect:true},{id:"c",text:"Threads require more memory",isCorrect:false},{id:"d",text:"Threads cannot be scheduled",isCorrect:false}], xpReward:10 },
];
